-- Seed: the catalogue as it stands in DevicesScreen.kt on 2026-08-24, plus the
-- three cards approved today (Alpine Silence, TheraSpecs, TheraSpecs FL-Pro).
-- Idempotent: re-running updates the English copy rather than duplicating rows.

insert into public.shop_groups (key, title, blurb, sort) values
  ('nerve_stimulation', 'Nerve stimulation', 'Send a small electrical or magnetic signal to a nerve involved in migraine.', 10),
  ('light_and_glare', 'Light and glare', 'For light sensitivity between and during attacks, on screens and off.', 20),
  ('prodrome', 'Prodrome management', 'For the early warning signs, before an attack fully arrives.', 30),
  ('nausea', 'Nausea', 'For when the sickness is the worst part.', 40),
  ('triggers', 'Trigger management', 'Aimed at stress and recovery, which for a lot of people is the trigger rather than the attack.', 50),
  ('heat_and_cold', 'Heat and cold', 'The oldest idea on this page, done with a machine.', 60),
  ('sound_and_noise', 'Sound and noise', 'For noise sensitivity, and for protecting the sleep that keeps attacks away.', 25)
on conflict (key) do update set title = excluded.title, blurb = excluded.blurb, sort = excluded.sort, updated_at = now();

insert into public.shop_items (key, group_key, name, what, evidence, pros, cons, rating, rating_source, rating_url, icon_key, photo_path, access, safety_note, sort) values
  ('cefaly', 'nerve_stimulation', 'CEFALY', 'Headband that stimulates the trigeminal nerve on the forehead. Separate acute and prevention programmes.', 'The best studied device on this list. Randomised trials support both stopping an attack and reducing how often they come.', '{}', '{}', null, null, null, 'cefaly', null, 'otc', null, 10),
  ('nerivio', 'nerve_stimulation', 'Nerivio', 'Armband worn on the upper arm during an attack. Stimulates nerves in the arm to dampen pain signals.', 'Randomised trial evidence for acute treatment, and later evidence for prevention. Needs a prescription.', '{}', '{}', null, null, null, 'nerivio', null, 'prescription', null, 20),
  ('gammacore', 'nerve_stimulation', 'gammaCore', 'Handheld unit held against the neck to stimulate the vagus nerve.', 'Trial evidence in migraine and stronger evidence in cluster headache. Needs a prescription.', '{}', '{}', null, null, null, 'gammacore', null, 'prescription', null, 30),
  ('stms_savi_dual', 'nerve_stimulation', 'sTMS (SAVI Dual)', 'Device held at the back of the head that delivers single magnetic pulses.', 'Studied for attacks with aura and for prevention. Bulkier and pricier than most. Needs a prescription.', '{}', '{}', null, null, null, 'stms', null, 'prescription', null, 40),
  ('relivion', 'nerve_stimulation', 'Relivion', 'Headset that stimulates the trigeminal and occipital nerves at the same time.', 'Newer than the others, with less independent data behind it so far. Needs a prescription.', '{}', '{}', null, null, null, 'relivion', null, 'prescription', null, 50),
  ('quell', 'nerve_stimulation', 'Quell', 'Band worn on the calf that delivers TENS-style stimulation.', 'Built for chronic pain generally. Migraine-specific evidence is thin, so treat it as an experiment.', '{}', '{}', null, null, null, 'quell', null, 'otc', null, 60),
  ('avulux_glasses', 'light_and_glare', 'Avulux glasses', 'Lenses that filter out most blue, amber and red light while letting green through.', 'A randomised trial in migraine backs the filter approach. Worth knowing they are much darker than normal tinted glasses.', '{}', '{}', null, null, null, 'avulux', null, 'otc', null, 70),
  ('theraspecs', 'light_and_glare', 'TheraSpecs', 'FL-41 tinted glasses, indoor and outdoor versions.', 'FL-41 tint has been studied for light sensitivity for decades. Cheaper than Avulux and easier to wear all day.', '{}', '{}', null, null, null, 'theraspecs', null, 'otc', null, 80),
  ('allay_lamp', 'light_and_glare', 'Allay Lamp', 'Lamp that emits a narrow band of green light you can sit and read under during an attack.', 'Comes out of Harvard research showing green light is the least aggravating wavelength. Small studies only.', '{}', '{}', null, null, null, 'allay', null, 'otc', null, 90),
  ('breo_see_7', 'prodrome', 'Breo See 7', 'Heated eye massager with hot and cold compress and gentle vibration, for eye strain and light sensitivity.', 'Eases eye strain and light sensitivity with heat and gentle pressure around the eyes, right when an attack is building.', array['Adjustable heat and pressure','Easy returns, responsive support','Good build quality'], array['Tight at the sides at first','Overuse can trigger a headache','Units failing just past warranty'], '4.2/5', 'Trustpilot, 137 reviews', 'https://www.trustpilot.com/review/us.breo.com', 'breo_see7', 'breo_see_7.png', 'otc', 'Compression-based eye massagers raise pressure inside the eye, so anyone with glaucoma, ocular hypertension or a history of eye surgery should check with their doctor first.', 100),
  ('breo_idream_5s', 'prodrome', 'Breo iDream 5S', 'Full-head massager with air pressure, kneading and heat across scalp, temples and eyes, run from your phone.', 'Eases head and temple pressure with kneading and heat across the scalp, right where tension builds during an attack.', array['Covers scalp, temples and eyes','Detachable eye cover','Good build quality'], array['Bulky to wear','Battery charging issues reported','Shipping can be slow'], '4.2/5', 'Trustpilot, 137 reviews', 'https://www.trustpilot.com/review/us.breo.com', 'breo_idream', 'breo_idream_5s.png', 'otc', null, 110),
  ('breo_ineck_3_pro', 'prodrome', 'Breo iNeck 3 Pro', 'Wraparound neck massager with deep kneading, air pressure and heat, controlled from your phone.', 'Eases neck tension, one of the most common migraine triggers, with kneading and heat before it escalates.', array['Kneading + heat combo','Adjustable via the app','Cordless, easy to wear','Responsive customer service'], array['Some units stop working early','Battery charging issues reported','Shipping can be slow'], '4.2/5', 'Trustpilot, 137 reviews', 'https://www.trustpilot.com/review/us.breo.com', 'breo_neck', 'breo_ineck_3_pro.png', 'otc', null, 120),
  ('reliefband', 'nausea', 'Reliefband', 'Wristband that stimulates the median nerve to settle nausea.', 'Cleared for nausea and vomiting rather than for migraine. Useful if sickness is the part that floors you.', '{}', '{}', null, null, null, 'reliefband', null, 'otc', null, 130),
  ('apollo_neuro', 'triggers', 'Apollo Neuro', 'Silent, soothing vibrations you wear on your wrist or ankle. Calms you down in minutes, rebalances your nervous system and lifts your HRV.', 'Built by neuroscientists, with published work on stress, sleep and HRV. Most useful if stress or broken sleep are among your triggers.', '{}', '{}', null, null, null, 'apollo', 'apollo_neuro.png', 'otc', null, 140),
  ('calmigo', 'triggers', 'CalmiGo', 'Handheld device that paces your breathing and gives feedback as you go.', 'Studied for stress and anxiety. Any migraine benefit is indirect, through the trigger rather than the attack.', '{}', '{}', null, null, null, 'calmigo', null, 'otc', null, 150),
  ('heartmath_inner_balance', 'triggers', 'HeartMath Inner Balance', 'Ear or finger sensor that coaches heart rate variability breathing through an app.', 'Biofeedback has real support as a preventive approach. This is one of several ways to do it, not the only one.', '{}', '{}', null, null, null, 'heartmath', null, 'otc', null, 160),
  ('thermazone', 'heat_and_cold', 'ThermaZone', 'Circulates hot or cold water through a head or neck pad at a steady temperature.', 'No migraine trials to speak of. It is a more controllable ice pack, and priced accordingly.', '{}', '{}', null, null, null, 'thermazone', null, 'otc', null, 170),
  ('alpine_silence', 'sound_and_noise', 'Alpine Silence', 'Everyday earplugs with a 22 dB filter and four tip sizes. Takes the sharpness out of a room without cutting you off from it.', 'Most useful if noise is one of your triggers, or if the room never gets quiet enough to sleep properly.', array['Takes the edge off a loud room','You can still follow a conversation','Soft enough to sleep in'], array['Tips can work loose over a long day','Not ideal for side sleepers','Some find 22 dB not enough on transport'], null, null, null, 'rel_earplugs', 'alpine_silence.png', 'otc', null, 175),
  ('theraspecs_fl41', 'light_and_glare', 'TheraSpecs', 'FL-41 tinted lenses in indoor, outdoor and prescription frames. A different tint from blue-light computer glasses, aimed at light sensitivity rather than eye strain.', 'FL-41 is the tint with the most research behind it, going back thirty years. Most useful if strip lighting or bright sun are what set you off.', array['Strip lights and screens stop biting','Cuts the glare that makes driving painful','Some report fewer attacks wearing them'], array['Ships from the US','Lenses are visibly rose-tinted'], null, null, null, 'rel_fl41_glasses', 'theraspecs_fl41.jpg', 'otc', null, 82),
  ('theraspecs_fl_pro', 'light_and_glare', 'TheraSpecs FL-Pro', 'Their strongest lens for screens, LEDs and strip lighting. Same frames, deeper tint.', 'The pair for the hours in front of a screen, where the everyday tint is not enough.', array['Takes the flicker out of LEDs','The strongest tint they make','Three strengths to choose from'], array['Colours shift on screen','Deep rose tint, people notice','Ships from the US'], null, null, null, 'rel_fl41_screen', 'theraspecs_fl_pro.jpg', 'otc', null, 84)
on conflict (key) do update set
  group_key = excluded.group_key, name = excluded.name, what = excluded.what,
  evidence = excluded.evidence, pros = excluded.pros, cons = excluded.cons,
  rating = excluded.rating, rating_source = excluded.rating_source, rating_url = excluded.rating_url,
  icon_key = excluded.icon_key, photo_path = excluded.photo_path, access = excluded.access,
  safety_note = excluded.safety_note, sort = excluded.sort, updated_at = now();

insert into public.shop_item_links (item_key, slug, countries, url, code, note, sort) values
  ('breo_see_7', 'default', null, 'https://us.breo.com/?ref=ME-SERIES', 'ME-SERIES', '$25 off with code ME-SERIES', 0),
  ('breo_idream_5s', 'default', null, 'https://us.breo.com/?ref=ME-SERIES', 'ME-SERIES', '$25 off with code ME-SERIES', 0),
  ('breo_ineck_3_pro', 'default', null, 'https://us.breo.com/?ref=ME-SERIES', 'ME-SERIES', '$25 off with code ME-SERIES', 0),
  ('apollo_neuro', 'default', null, 'https://apolloneuro.com/migraineme', null, '$99 off, 30-day trial', 0),
  ('alpine_silence', 'us', array['US'], 'https://www.awin1.com/cread.php?awinmid=101957&awinaffid=3026993&ued=https%3A%2F%2Fwww.alpinehearingprotection.com%2Fproducts%2Fsilence', null, null, 10),
  ('alpine_silence', 'eu', array['NL','BE','DE','FR','ES','IT','AT','PT','IE','LU','DK','SE','FI','PL','CZ'], 'https://www.awin1.com/cread.php?awinmid=101953&awinaffid=3026993&ued=https%3A%2F%2Fwww.alpine.nl%2Fproducts%2Fsilence', null, null, 20),
  ('theraspecs_fl41', 'default', null, 'https://www.theraspecs.com/fl-41-glasses/', null, null, 0),
  ('theraspecs_fl_pro', 'default', null, 'https://www.theraspecs.com/fl-pro/', null, null, 0)
on conflict (item_key, slug) do update set
  countries = excluded.countries, url = excluded.url, code = excluded.code,
  note = excluded.note, sort = excluded.sort, updated_at = now();
