// The translation boundary for anything the BACKEND renders: push notification
// titles and bodies, in-app notification rows written by workers, transactional
// email, and messages handed straight back in an HTTP response.
//
// This file is IDENTICAL in the MigraineMe (Android) repo and the
// migraineme-ios repo — both deploy edge functions to the same Supabase
// project, so there is exactly one server i18n layer. Change it in one repo,
// copy it to the other, byte for byte.
//
// The contract, same as Strings.kt / lib/strings.ts on the clients:
//
//   - The ENGLISH TEXT IS THE KEY. A call site reads as plain English, and a
//     missing translation degrades to that same English rather than to a raw
//     key or a crash. That fallback is why a new push can ship before its
//     translation does.
//   - Translation happens at the point of RENDERING and nowhere else. Nothing
//     translated may reach a stored value: not a column another query will
//     match on (user_triggers.label, insight groupings and DeterministicMapper
//     all branch on English), not an FCM `data` field the client branches on.
//     The `notification` block is display; the `data` block is not. A row
//     translated at INSERT time is also frozen in whatever language the user
//     had that day, while a stored English row follows them when they switch.
//
// Two translation tables feed t(), because two generators exist:
//
//   ./translations.ts    — single file, "%1$s" positional placeholders.
//                          GENERATED by tools/i18n/generate.py in the
//                          MigraineMe (Android) repo from its
//                          tools/i18n/translations/*.json, restricted to
//                          server_strings.json.
//   ./translations/*.ts  — one file per language, "{0}" placeholders.
//                          GENERATED by tools/i18n/gen_server_i18n.py in the
//                          migraineme-ios repo from its
//                          tools/i18n/translations/*.json plus
//                          ./manual_keys.json.
//
// Each generator owns only its own output file(s) and never touches the
// other's; this module merges the two at load. The placeholder styles never
// collide because a given English key uses one style or the other, and
// format() substitutes both.

import { TABLES as SUBSET_TABLES } from "./translations.ts";
import DE from "./translations/de.ts";
import ES from "./translations/es.ts";
import FR from "./translations/fr.ts";
import IT from "./translations/it.ts";
import NL from "./translations/nl.ts";
import PT from "./translations/pt.ts";

export type Lang = "en" | "de" | "es" | "nl" | "fr" | "it" | "pt";

export const LANGS: readonly Lang[] = ["en", "de", "es", "nl", "fr", "it", "pt"];

const SPLIT_TABLES: Partial<Record<Lang, Record<string, string>>> = {
  de: DE,
  es: ES,
  nl: NL,
  fr: FR,
  it: IT,
  pt: PT,
};

// Merged lazily and cached: an edge function cold-starts per request and most
// render only a handful of strings in one language.
const MERGED: Partial<Record<Lang, Record<string, string>>> = {};

function tableFor(lang: Lang): Record<string, string> {
  let table = MERGED[lang];
  if (!table) {
    table = { ...(SPLIT_TABLES[lang] ?? {}), ...(SUBSET_TABLES[lang] ?? {}) };
    MERGED[lang] = table;
  }
  return table;
}

/** Narrow an arbitrary value (a DB column, a request field) to a supported language. */
export function toLang(code: unknown): Lang {
  const c = String(code ?? "").toLowerCase();
  return (LANGS as readonly string[]).includes(c) ? (c as Lang) : "en";
}

/** iOS-repo name for toLang. */
export const asLang = toLang;

/**
 * Substitute positional arguments into a pattern, in either placeholder style:
 * "%1$s" (1-indexed, Android Strings.kt convention) or "{0}" (0-indexed,
 * lib/strings.ts convention). Placeholders are positional because word order
 * moves in translation; a translator must be free to reorder without touching
 * code. An unmatched placeholder is left in place.
 */
function format(pattern: string, args: unknown[]): string {
  if (args.length === 0) return pattern;
  return pattern
    .replace(/%(\d+)\$s/g, (whole, idx) => {
      const arg = args[Number(idx) - 1];
      return arg === undefined ? whole : String(arg);
    })
    .replace(/\{(\d+)\}/g, (whole, idx) => {
      const arg = args[Number(idx)];
      return arg === undefined ? whole : String(arg);
    });
}

/**
 * Translate, substituting positional arguments. The English key keeps its
 * placeholders — "%1$s commented" is what gets translated — and the arguments
 * go in afterwards. An untranslated key renders its English source, which is
 * why callers pass real English rather than a symbolic key.
 */
export function t(lang: Lang, en: string, ...args: unknown[]): string {
  const pattern = lang === "en" ? en : (tableFor(lang)[en] ?? en);
  return format(pattern, args);
}

/** iOS-repo name for t. */
export const translate = t;

/**
 * Bind a language once, then render:
 *
 *   const t = translatorFor(lang);
 *   t("Today's risk: {0}", t("High"))
 *
 * The iOS-repo generator finds server strings by scanning for `t("…")` in this
 * directory tree, so keep call sites written as a literal first argument. A
 * string assembled in a variable still translates at runtime — English is the
 * key — but it will not be picked up for translation, which looks exactly like
 * a missing translation later.
 */
export function translatorFor(lang: Lang): (en: string, ...args: unknown[]) => string {
  return (en: string, ...args: unknown[]) => t(lang, en, ...args);
}

// ─── Recipient language ────────────────────────────────────────────────────
//
// profiles.lang, mirrored from the device by the apps. profiles has no app_id —
// language is a fact about the person, not the app. Any read failure yields
// English, because a push in the wrong language beats no push at all.

// Structurally minimal on purpose. Spelling out the query-builder shape would
// mean re-deriving supabase-js's internal PostgrestFilterBuilder types here, and
// getting that subtly wrong fails the DEPLOY rather than anything we can catch
// locally. The functions that call these already hold a real client.
// deno-lint-ignore no-explicit-any
type MinimalClient = { from: (table: string) => any };

/** One user's display language. */
export async function getLang(sb: MinimalClient, userId: string): Promise<Lang> {
  try {
    const { data } = await sb.from("profiles").select("lang").eq("user_id", userId).maybeSingle();
    return toLang((data as { lang?: unknown } | null)?.lang);
  } catch {
    return "en";
  }
}

/** iOS-repo name for getLang. */
export const langForUser = getLang;

/**
 * Languages for many users at once, as user_id → Lang, for the fan-out workers
 * (one push per user at the end of a run would otherwise cost a round trip per
 * recipient). Users absent from the result are absent from the map; read it
 * with `map.get(id) ?? "en"`.
 */
export async function getLangs(
  sb: MinimalClient,
  userIds: string[],
): Promise<Map<string, Lang>> {
  const out = new Map<string, Lang>();
  if (userIds.length === 0) return out;
  try {
    const { data } = await sb.from("profiles").select("user_id, lang").in("user_id", userIds);
    for (const r of (data ?? []) as Array<{ user_id: string; lang?: unknown }>) {
      out.set(r.user_id, toLang(r.lang));
    }
  } catch {
    // Leave the map empty; every caller falls back to English per user.
  }
  return out;
}

/** iOS-repo name for getLangs. */
export const langsForUsers = getLangs;

// ─── Model output ──────────────────────────────────────────────────────────

/** Endonym for each language, for instructing a model which one to write in. */
const LANGUAGE_NAMES: Record<Lang, string> = {
  en: "English",
  de: "German",
  es: "Spanish",
  nl: "Dutch",
  fr: "French",
  it: "Italian",
  pt: "European Portuguese",
};

/**
 * A line to append to an LLM system prompt so its prose comes back in the
 * user's display language.
 *
 * Translation tables only cover strings we wrote. Anything a model composes at
 * request time — daily insights, recommendations, the congratulation card, chat
 * replies — has to be generated in the right language in the first place, or it
 * arrives in English on an otherwise translated screen. Returns "" for English
 * so the prompt is untouched in the common case.
 */
export function languageDirective(lang: Lang): string {
  if (lang === "en") return "";
  const name = LANGUAGE_NAMES[lang];
  return `\n\nIMPORTANT: write every user-facing string in your response in ${name}. `
    + `Keep JSON keys, enum values and any identifiers exactly as specified in English. `
    + `Use the natural, informal register a health app would use with someone it knows well.`;
}
