#!/usr/bin/env python3
"""
Generate the translation tables from the JSON translations.

Two outputs, one source:

  StringsXx.kt                              — the app's tables, all entries.
  supabase/functions/_shared/translations.ts — the edge functions' table, only
                                               the strings the backend renders.

Translations are authored in tools/i18n/translations/<lang>.json and compiled
here, so the checker has one clean source to validate and neither the Kotlin nor
the TypeScript ever has to be hand-edited. Regenerating is safe and idempotent.

The TS module is deliberately a SUBSET, listed in tools/i18n/server_strings.json.
Shipping all six full tables would put roughly 700 KB of strings into every edge
function bundle to serve the dozen or so a backend actually renders, and an edge
function is cold-started per request. Subsetting keeps the same source of truth
and the same length gate while the deployed artefact stays small; adding a
backend string means adding it to server_strings.json, which is also what puts
it in front of the extractor and the checker.

Refuses to emit a table that fails its length budget, so an overflow cannot reach
a build by accident.
"""

import json
import os
import subprocess
import sys

TRANS = "tools/i18n/translations"
DEST = "app/src/main/java/com/migraineme"
SERVER = "tools/i18n/server_strings.json"
TS_DEST = "supabase/functions/_shared/translations.ts"
LANGS = {
    "de": ("De", "DE", "German"),
    "es": ("Es", "ES", "Spanish"),
    "nl": ("Nl", "NL", "Dutch"),
    "fr": ("Fr", "FR", "French"),
    "it": ("It", "IT", "Italian"),
    "pt": ("Pt", "PT", "Portuguese"),
}

HEADER = '''package com.migraineme

/**
 * {name} display strings, keyed by the English source text.
 *
 * GENERATED by tools/i18n/generate.py from tools/i18n/translations/{code}.json.
 * Do not edit here — edit the JSON and regenerate, so the length gate in
 * tools/i18n/check_lengths.py stays authoritative.
 *
 * Entries are held to the length budget of their call site, so labels that
 * cannot wrap stay inside the space the English occupies. A key absent here
 * renders its English source, so partial coverage is safe.
 *
 * {done} entries.
 */
internal val {up}_STRINGS: Map<String, String> = mapOf(
'''


def esc(s):
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\t", "\\t")
         .replace("$", "\\$")
    )


def main():
    only = [a for a in sys.argv[1:] if not a.startswith("-")]
    langs = only or list(LANGS)

    check = subprocess.run(
        [sys.executable, "tools/i18n/check_lengths.py", *langs],
        capture_output=True, text=True,
    )
    if check.returncode != 0:
        print(check.stdout)
        sys.exit("length gate failed; fix the overflows above before generating")

    for code in langs:
        title, up, name = LANGS[code]
        path = os.path.join(TRANS, f"{code}.json")
        table = {}
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                table = json.load(fh)

        out = os.path.join(DEST, f"Strings{title}.kt")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(name=name, code=code, up=up, done=len(table)))
            for en in sorted(table):
                fh.write(f'    "{esc(en)}" to "{esc(table[en])}",\n')
            fh.write(")\n")
        print(f"{out}  {len(table)} entries")

    # The edge functions' subset. Only emitted on a full run: a single-language
    # invocation would otherwise rewrite the module with five languages missing.
    if not only:
        write_ts()


TS_HEADER = '''// Backend translation tables, keyed by the English source text.
//
// GENERATED by tools/i18n/generate.py from tools/i18n/translations/*.json,
// restricted to the strings listed in tools/i18n/server_strings.json.
// Do not edit here — edit the JSON and regenerate, so the length gate in
// tools/i18n/check_lengths.py stays authoritative for backend copy too.
//
// This is a SUBSET of what the app carries. The app has ~1240 strings per
// language; an edge function renders about a dozen, cold-starts per request,
// and has no reason to carry the rest. Adding a backend string means adding it
// to server_strings.json, which is also what puts it in front of the extractor,
// the length gate and the translators.
//
// English is the key, not merely the default: a missing entry renders the
// English that was passed in, so a half-translated language is safe to ship
// and canonical data stays English everywhere. See LangPrefs.kt.

export type Lang = "en" | "de" | "es" | "nl" | "fr" | "it" | "pt";

export const LANGS: readonly Lang[] = ["en", "de", "es", "nl", "fr", "it", "pt"];

export const TABLES: Record<string, Record<string, string>> = {
'''


def ts(s):
    """Escape for a double-quoted TS string literal."""
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\t", "\\t")
    )


def write_ts():
    with open(SERVER, encoding="utf-8") as fh:
        keys = [e["en"] for e in json.load(fh).get("entries", [])]

    os.makedirs(os.path.dirname(TS_DEST), exist_ok=True)
    with open(TS_DEST, "w", encoding="utf-8") as fh:
        fh.write(TS_HEADER)
        for code in LANGS:
            path = os.path.join(TRANS, f"{code}.json")
            table = {}
            if os.path.isfile(path):
                with open(path, encoding="utf-8") as tf:
                    table = json.load(tf)
            fh.write(f'  {code}: {{\n')
            for en in keys:
                if en in table:
                    fh.write(f'    "{ts(en)}": "{ts(table[en])}",\n')
            fh.write("  },\n")
        fh.write("};\n")
    print(f"{TS_DEST}  {len(keys)} keys x {len(LANGS)} languages")


if __name__ == "__main__":
    main()
