-- Food search in the user's own language.
--
-- usda_foods.description is English only, and the app's typed food search is
-- USDA FoodData Central (English) with search_usda_foods as the fallback. This
-- adds a per-language name table for every usda_foods row (de/es/nl/fr/it/pt,
-- translated once with Claude Sonnet, see tools/usda_i18n/) and teaches the
-- RPC a `lang` parameter. Non-English clients now call the RPC FIRST with their
-- language and only fall back to USDA when it returns nothing.
--
-- Search per language: a stored tsvector using that language's stemmer over the
-- unaccented name, prefix-matched on every word ("kaa ched" finds "Kaas,
-- cheddar"), plus a trigram ILIKE fallback for typos. If the language search
-- finds nothing the English search runs, so "pizza" or a brand still works.
--
-- The RPC now also returns description_en (the USDA name) so clients can send
-- the English name to classify-food-risks and share its cache across
-- languages. Return columns changed, so the old signature is dropped; old app
-- versions call it with (search_query, result_limit) which still resolves.
--
-- Both Supabase projects (MigraineMe qykflarpibofvffmzghi, MeSeries/VertigoMe
-- vpwnhpwiwxwoyjfytiye) hold the identical 13,661-row usda_foods, so this file
-- is byte-identical in both repos. Data load: tools/usda_i18n/load.py.

create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;

-- unaccent() is STABLE, which a generated column/index expression cannot use.
-- This wrapper pins the dictionary and is safe to mark IMMUTABLE.
create or replace function public.usda_unaccent(text)
returns text
language sql
immutable
parallel safe
strict
set search_path = ''
as $$
  select extensions.unaccent('extensions.unaccent'::regdictionary, $1)
$$;

create or replace function public.usda_ts_config(lang text)
returns regconfig
language sql
immutable
parallel safe
strict
set search_path = ''
as $$
  select case lang
    when 'de' then 'german'::regconfig
    when 'es' then 'spanish'::regconfig
    when 'nl' then 'dutch'::regconfig
    when 'fr' then 'french'::regconfig
    when 'it' then 'italian'::regconfig
    when 'pt' then 'portuguese'::regconfig
    else 'english'::regconfig
  end
$$;

create table if not exists public.usda_foods_i18n (
  fdc_id integer not null references public.usda_foods(fdc_id) on delete cascade,
  lang text not null check (lang in ('de','es','nl','fr','it','pt')),
  description text not null check (length(description) between 1 and 400),
  description_lower text generated always as (lower(public.usda_unaccent(description))) stored,
  search_vector tsvector generated always as
    (to_tsvector(public.usda_ts_config(lang), public.usda_unaccent(description))) stored,
  primary key (fdc_id, lang)
);

comment on table public.usda_foods_i18n is
  'Translated usda_foods.description per app language (de/es/nl/fr/it/pt). Public reference data; generated by tools/usda_i18n/.';

create index if not exists usda_foods_i18n_lang_search_idx
  on public.usda_foods_i18n using gin (search_vector);
create index if not exists usda_foods_i18n_lang_trgm_idx
  on public.usda_foods_i18n using gin (description_lower extensions.gin_trgm_ops);

alter table public.usda_foods_i18n enable row level security;

drop policy if exists "usda_foods_i18n public read" on public.usda_foods_i18n;
create policy "usda_foods_i18n public read"
  on public.usda_foods_i18n for select
  to anon, authenticated
  using (true);

grant select on public.usda_foods_i18n to anon, authenticated;
grant all on public.usda_foods_i18n to service_role;

-- Every word of the query as a prefix term: "kaa ched" -> 'kaa':* & 'ched':*
create or replace function public.usda_prefix_tsquery(cfg regconfig, q text)
returns tsquery
language sql
immutable
parallel safe
strict
set search_path = ''
as $$
  select nullif(
    regexp_replace(plainto_tsquery(cfg, q)::text, '''( |$)', ''':*\1', 'g'),
    ''
  )::tsquery
$$;

drop function if exists public.search_usda_foods(text, integer);

create or replace function public.search_usda_foods(
  search_query text,
  result_limit integer default 20,
  lang text default 'en'
)
returns table(
  fdc_id integer,
  description text,
  description_en text,
  data_type text,
  food_category text,
  serving_size double precision,
  serving_size_unit text,
  rank real
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  q text := btrim(coalesce(search_query, ''));
  l text := lower(coalesce(lang, 'en'));
  cfg regconfig;
  tsq tsquery;
  qlower text;
begin
  if q = '' then
    return;
  end if;
  result_limit := least(greatest(coalesce(result_limit, 20), 1), 50);

  if l in ('de','es','nl','fr','it','pt') then
    cfg := public.usda_ts_config(l);
    tsq := public.usda_prefix_tsquery(cfg, public.usda_unaccent(q));
    qlower := lower(public.usda_unaccent(q));

    return query
    select
      f.fdc_id,
      i.description,
      f.description as description_en,
      f.data_type,
      f.food_category,
      f.serving_size,
      f.serving_size_unit,
      ts_rank(i.search_vector, tsq) as rank
    from public.usda_foods_i18n i
    join public.usda_foods f on f.fdc_id = i.fdc_id
    where i.lang = l
      and tsq is not null
      and i.search_vector @@ tsq
    order by
      -- whole-word (stemmed) hits first; prefix-only hits after. Stemmers cut
      -- "kaas" to "kas", so without this "kastanje" would tie with "Kaas".
      (i.search_vector @@ plainto_tsquery(cfg, public.usda_unaccent(q))) desc,
      case f.data_type
        when 'Foundation' then 0
        when 'SR Legacy' then 1
        when 'Survey (FNDDS)' then 2
        else 3
      end,
      rank desc,
      length(i.description)
    limit result_limit;
    if found then
      return;
    end if;

    -- typo tolerance: trigram substring match on the unaccented lower name
    return query
    select
      f.fdc_id,
      i.description,
      f.description as description_en,
      f.data_type,
      f.food_category,
      f.serving_size,
      f.serving_size_unit,
      extensions.similarity(i.description_lower, qlower) as rank
    from public.usda_foods_i18n i
    join public.usda_foods f on f.fdc_id = i.fdc_id
    where i.lang = l
      and i.description_lower like '%' || qlower || '%'
    order by
      case f.data_type
        when 'Foundation' then 0
        when 'SR Legacy' then 1
        when 'Survey (FNDDS)' then 2
        else 3
      end,
      rank desc,
      length(i.description)
    limit result_limit;
    if found then
      return;
    end if;
    -- nothing in the user's language: fall through to English
  end if;

  return query
  select
    f.fdc_id,
    f.description,
    f.description as description_en,
    f.data_type,
    f.food_category,
    f.serving_size,
    f.serving_size_unit,
    ts_rank(to_tsvector('english', f.description), plainto_tsquery('english', q)) as rank
  from public.usda_foods f
  where to_tsvector('english', f.description) @@ plainto_tsquery('english', q)
  order by
    case f.data_type
      when 'Foundation' then 0
      when 'SR Legacy' then 1
      when 'Survey (FNDDS)' then 2
      else 3
    end,
    rank desc
  limit result_limit;
end;
$$;

grant execute on function public.search_usda_foods(text, integer, text) to anon, authenticated, service_role;

notify pgrst, 'reload schema';
